- name: "Install memcached"
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - memcached

- name: "Copy memcached config files"
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '../files/memcached-conf', dest: '/etc/memcached.conf', owner: 'root', group: 'root', mode: '0400' }